"""
Pydantic models for all structured outputs in the risk detection layer.

These models are the central data contract between:
  - The rule engine (produces Signal objects)
  - Claude risk assessment (produces RiskOutput)
  - The audit log (persists RiskOutput as JSON)
  - The briefing generator (consumes RiskOutput)
  - The Streamlit dashboard (reads RiskOutput from audit log)
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator


class RiskLevel(str, Enum):
    LOW = "LOW"
    ELEVATED = "ELEVATED"
    HIGH = "HIGH"

    def __ge__(self, other: "RiskLevel") -> bool:
        order = [RiskLevel.LOW, RiskLevel.ELEVATED, RiskLevel.HIGH]
        return order.index(self) >= order.index(other)

    def __gt__(self, other: "RiskLevel") -> bool:
        order = [RiskLevel.LOW, RiskLevel.ELEVATED, RiskLevel.HIGH]
        return order.index(self) > order.index(other)

    @classmethod
    def max(cls, a: "RiskLevel", b: "RiskLevel") -> "RiskLevel":
        order = [cls.LOW, cls.ELEVATED, cls.HIGH]
        return a if order.index(a) >= order.index(b) else b


class SignalType(str, Enum):
    BALANCE_SHEET = "BALANCE_SHEET"
    FUNDING = "FUNDING"
    EARNINGS = "EARNINGS"
    MARKET = "MARKET"
    CREDIT_RATING = "CREDIT_RATING"
    REGULATORY = "REGULATORY"
    MANAGEMENT = "MANAGEMENT"
    MACRO = "MACRO"
    OTHER = "OTHER"


class SourceRef(BaseModel):
    """Reference to the source document that supports a signal."""

    document_type: str = Field(description="e.g. '10-Q', 'news article', 'price data'")
    document_date: str = Field(description="ISO-8601 date string")
    section: Optional[str] = Field(default=None, description="e.g. 'Note 4', 'Item 7A'")
    excerpt: Optional[str] = Field(
        default=None,
        max_length=500,
        description="Short verbatim excerpt supporting this signal",
    )
    chunk_id: Optional[str] = Field(default=None)


class Signal(BaseModel):
    """A single detected risk signal."""

    signal_type: SignalType
    description: str = Field(description="Plain-English description of the signal")
    severity: RiskLevel = Field(description="How severe this specific signal is")
    source_refs: list[SourceRef] = Field(default_factory=list)
    metric_value: Optional[float] = Field(
        default=None,
        description="Numeric value of the metric that triggered this signal, if applicable",
    )
    metric_name: Optional[str] = Field(
        default=None,
        description="Name of the metric (e.g. 'deposit_qoq_change')",
    )
    triggered_by_rule: bool = Field(
        default=False,
        description="True if this signal was triggered by the hard-threshold rule engine",
    )


class RiskOutput(BaseModel):
    """
    Structured risk assessment output for a single company.

    This is the central artifact produced by the risk agent and
    persisted in the audit log.
    """

    company: str
    ticker: str
    assessment_date: str = Field(description="ISO-8601 datetime string")
    risk_level: RiskLevel = Field(
        description="Overall risk level: LOW, ELEVATED, or HIGH"
    )
    signals: list[Signal] = Field(default_factory=list)
    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Model confidence in the overall risk assessment (0.0–1.0)",
    )
    rule_engine_flags: list[str] = Field(
        default_factory=list,
        description="List of rule engine threshold names that were triggered",
    )
    narrative_summary: Optional[str] = Field(
        default=None,
        description="Plain-English briefing generated by the output layer",
    )
    human_review_status: str = Field(
        default="PENDING",
        description="PENDING | REVIEWED | ESCALATED",
    )
    industry: Optional[str] = Field(default=None)
    sector: Optional[str] = Field(default=None)
    market_cap_bucket: Optional[str] = Field(default=None)

    @field_validator("assessment_date", mode="before")
    @classmethod
    def coerce_date(cls, v: object) -> str:
        if isinstance(v, datetime):
            return v.isoformat()
        return str(v)

    def model_dump_audit(self) -> dict:
        """Serialize to a dict suitable for JSON storage in the audit log."""
        return self.model_dump(mode="json")

    @property
    def is_elevated_or_high(self) -> bool:
        return self.risk_level in (RiskLevel.ELEVATED, RiskLevel.HIGH)
